/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-d1-sqlite'
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from '@payloadcms/db-d1-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-d1-sqlite/drizzle'

export const users_sessions = sqliteTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    expiresAt: text('expires_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = sqliteTable(
  'users',
  {
    id: integer('id').primaryKey(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text('email').notNull(),
    resetPasswordToken: text('reset_password_token'),
    resetPasswordExpiration: text('reset_password_expiration').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text('salt'),
    hash: text('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = sqliteTable(
  'media',
  {
    id: integer('id').primaryKey(),
    alt: text('alt').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const bot_speech_examples = sqliteTable(
  'bot_speech_examples',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    example: text('example'),
  },
  (columns) => [
    index('bot_speech_examples_order_idx').on(columns._order),
    index('bot_speech_examples_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [bot.id],
      name: 'bot_speech_examples_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const bot = sqliteTable(
  'bot',
  {
    id: integer('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    created_date: text('created_date').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    name: text('name').notNull(),
    picture: integer('picture_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    gender: text('gender', {
      enum: ['male', 'female', 'non-binary', 'other', 'prefer-not-to-say'],
    }),
    age: numeric('age'),
    description: text('description'),
    system_prompt: text('system_prompt').notNull(),
    is_public: integer('is_public', { mode: 'boolean' }).default(false),
    greeting: text('greeting'),
    slug: text('slug').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('bot_user_idx').on(columns.user),
    index('bot_picture_idx').on(columns.picture),
    uniqueIndex('bot_slug_idx').on(columns.slug),
    index('bot_updated_at_idx').on(columns.updatedAt),
    index('bot_created_at_idx').on(columns.createdAt),
  ],
)

export const bot_rels = sqliteTable(
  'bot_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    knowledgeCollectionsID: integer('knowledge_collections_id'),
  },
  (columns) => [
    index('bot_rels_order_idx').on(columns.order),
    index('bot_rels_parent_idx').on(columns.parent),
    index('bot_rels_path_idx').on(columns.path),
    index('bot_rels_knowledge_collections_id_idx').on(columns.knowledgeCollectionsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [bot.id],
      name: 'bot_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['knowledgeCollectionsID']],
      foreignColumns: [knowledge_collections.id],
      name: 'bot_rels_knowledge_collections_fk',
    }).onDelete('cascade'),
  ],
)

export const api_key = sqliteTable(
  'api_key',
  {
    id: integer('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    nickname: text('nickname').notNull(),
    provider: text('provider', {
      enum: ['openai', 'anthropic', 'google', 'huggingface', 'other'],
    }).notNull(),
    key: text('key').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('api_key_user_idx').on(columns.user),
    index('api_key_updated_at_idx').on(columns.updatedAt),
    index('api_key_created_at_idx').on(columns.createdAt),
  ],
)

export const mood = sqliteTable(
  'mood',
  {
    id: integer('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    timestamp: text('timestamp').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    mood: text('mood', {
      enum: [
        'very-happy',
        'happy',
        'content',
        'neutral',
        'sad',
        'very-sad',
        'anxious',
        'excited',
        'angry',
        'frustrated',
      ],
    }).notNull(),
    note: text('note'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('mood_user_idx').on(columns.user),
    index('mood_updated_at_idx').on(columns.updatedAt),
    index('mood_created_at_idx').on(columns.createdAt),
  ],
)

export const knowledge_tags = sqliteTable(
  'knowledge_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    tag: text('tag'),
  },
  (columns) => [
    index('knowledge_tags_order_idx').on(columns._order),
    index('knowledge_tags_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [knowledge.id],
      name: 'knowledge_tags_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const knowledge = sqliteTable(
  'knowledge',
  {
    id: integer('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    created_timestamp: text('created_timestamp').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    modified_timestamp: text('modified_timestamp').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    type: text('type', {
      enum: ['document', 'url', 'text', 'image', 'audio', 'video', 'code'],
    }).notNull(),
    tokens: numeric('tokens').default('0'),
    entry: text('entry').notNull(),
    knowledge_collection: integer('knowledge_collection_id')
      .notNull()
      .references(() => knowledge_collections.id, {
        onDelete: 'set null',
      }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('knowledge_user_idx').on(columns.user),
    index('knowledge_knowledge_collection_idx').on(columns.knowledge_collection),
    index('knowledge_updated_at_idx').on(columns.updatedAt),
    index('knowledge_created_at_idx').on(columns.createdAt),
  ],
)

export const knowledge_collections = sqliteTable(
  'knowledge_collections',
  {
    id: integer('id').primaryKey(),
    name: text('name').notNull(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    created_timestamp: text('created_timestamp').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    modified_timestamp: text('modified_timestamp').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    description: text('description'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('knowledge_collections_user_idx').on(columns.user),
    index('knowledge_collections_updated_at_idx').on(columns.updatedAt),
    index('knowledge_collections_created_at_idx').on(columns.createdAt),
  ],
)

export const knowledge_collections_rels = sqliteTable(
  'knowledge_collections_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    botID: integer('bot_id'),
  },
  (columns) => [
    index('knowledge_collections_rels_order_idx').on(columns.order),
    index('knowledge_collections_rels_parent_idx').on(columns.parent),
    index('knowledge_collections_rels_path_idx').on(columns.path),
    index('knowledge_collections_rels_bot_id_idx').on(columns.botID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [knowledge_collections.id],
      name: 'knowledge_collections_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['botID']],
      foreignColumns: [bot.id],
      name: 'knowledge_collections_rels_bot_fk',
    }).onDelete('cascade'),
  ],
)

export const conversation = sqliteTable(
  'conversation',
  {
    id: integer('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    created_timestamp: text('created_timestamp').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    modified_timestamp: text('modified_timestamp').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('conversation_user_idx').on(columns.user),
    index('conversation_updated_at_idx').on(columns.updatedAt),
    index('conversation_created_at_idx').on(columns.createdAt),
  ],
)

export const conversation_rels = sqliteTable(
  'conversation_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    botID: integer('bot_id'),
  },
  (columns) => [
    index('conversation_rels_order_idx').on(columns.order),
    index('conversation_rels_parent_idx').on(columns.parent),
    index('conversation_rels_path_idx').on(columns.path),
    index('conversation_rels_bot_id_idx').on(columns.botID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [conversation.id],
      name: 'conversation_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['botID']],
      foreignColumns: [bot.id],
      name: 'conversation_rels_bot_fk',
    }).onDelete('cascade'),
  ],
)

export const message = sqliteTable(
  'message',
  {
    id: integer('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    created_timestamp: text('created_timestamp').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    modified_timestamp: text('modified_timestamp').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    conversation: integer('conversation_id')
      .notNull()
      .references(() => conversation.id, {
        onDelete: 'set null',
      }),
    bot: integer('bot_id').references(() => bot.id, {
      onDelete: 'set null',
    }),
    byo_key: integer('byo_key', { mode: 'boolean' }).default(false),
    tokens: numeric('tokens').default('0'),
    entry: text('entry').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('message_user_idx').on(columns.user),
    index('message_conversation_idx').on(columns.conversation),
    index('message_bot_idx').on(columns.bot),
    index('message_updated_at_idx').on(columns.updatedAt),
    index('message_created_at_idx').on(columns.createdAt),
  ],
)

export const memory = sqliteTable(
  'memory',
  {
    id: integer('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    created_timestamp: text('created_timestamp').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    modified_timestamp: text('modified_timestamp').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    bot: integer('bot_id')
      .notNull()
      .references(() => bot.id, {
        onDelete: 'set null',
      }),
    conversation: integer('conversation_id').references(() => conversation.id, {
      onDelete: 'set null',
    }),
    tokens: numeric('tokens').default('0'),
    entry: text('entry').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('memory_user_idx').on(columns.user),
    index('memory_bot_idx').on(columns.bot),
    index('memory_conversation_idx').on(columns.conversation),
    index('memory_updated_at_idx').on(columns.updatedAt),
    index('memory_created_at_idx').on(columns.createdAt),
  ],
)

export const token_gifts = sqliteTable(
  'token_gifts',
  {
    id: integer('id').primaryKey(),
    sender: integer('sender_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    receiver: integer('receiver_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    message: text('message'),
    tokens: numeric('tokens').notNull(),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('token_gifts_sender_idx').on(columns.sender),
    index('token_gifts_receiver_idx').on(columns.receiver),
    index('token_gifts_updated_at_idx').on(columns.updatedAt),
    index('token_gifts_created_at_idx').on(columns.createdAt),
  ],
)

export const subscription_payments = sqliteTable(
  'subscription_payments',
  {
    id: integer('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    date: text('date').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    tokens: numeric('tokens').notNull(),
    amount: numeric('amount').notNull(),
    currency: text('currency', { enum: ['usd', 'eur', 'gbp'] }).notNull(),
    payment_method: text('payment_method', { enum: ['credit-card', 'paypal', 'stripe', 'other'] }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('subscription_payments_user_idx').on(columns.user),
    index('subscription_payments_updated_at_idx').on(columns.updatedAt),
    index('subscription_payments_created_at_idx').on(columns.createdAt),
  ],
)

export const subscription_tiers_features = sqliteTable(
  'subscription_tiers_features',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    feature: text('feature'),
  },
  (columns) => [
    index('subscription_tiers_features_order_idx').on(columns._order),
    index('subscription_tiers_features_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [subscription_tiers.id],
      name: 'subscription_tiers_features_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const subscription_tiers = sqliteTable(
  'subscription_tiers',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull(),
    cost: numeric('cost').notNull(),
    tokens: numeric('tokens').notNull(),
    currency: text('currency', { enum: ['usd', 'eur', 'gbp'] }).notNull(),
    billing_period: text('billing_period', { enum: ['monthly', 'yearly', 'one-time'] }).notNull(),
    is_active: integer('is_active', { mode: 'boolean' }).default(true),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('subscription_tiers_updated_at_idx').on(columns.updatedAt),
    index('subscription_tiers_created_at_idx').on(columns.createdAt),
  ],
)

export const token_packages = sqliteTable(
  'token_packages',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull(),
    cost: numeric('cost').notNull(),
    tokens: numeric('tokens').notNull(),
    currency: text('currency', { enum: ['usd', 'eur', 'gbp'] }).notNull(),
    description: text('description'),
    is_popular: integer('is_popular', { mode: 'boolean' }).default(false),
    is_active: integer('is_active', { mode: 'boolean' }).default(true),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('token_packages_updated_at_idx').on(columns.updatedAt),
    index('token_packages_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = sqliteTable(
  'payload_locked_documents',
  {
    id: integer('id').primaryKey(),
    globalSlug: text('global_slug'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = sqliteTable(
  'payload_locked_documents_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    botID: integer('bot_id'),
    'api-keyID': integer('api_key_id'),
    moodID: integer('mood_id'),
    knowledgeID: integer('knowledge_id'),
    knowledgeCollectionsID: integer('knowledge_collections_id'),
    conversationID: integer('conversation_id'),
    messageID: integer('message_id'),
    memoryID: integer('memory_id'),
    tokenGiftsID: integer('token_gifts_id'),
    subscriptionPaymentsID: integer('subscription_payments_id'),
    subscriptionTiersID: integer('subscription_tiers_id'),
    tokenPackagesID: integer('token_packages_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_bot_id_idx').on(columns.botID),
    index('payload_locked_documents_rels_api_key_id_idx').on(columns['api-keyID']),
    index('payload_locked_documents_rels_mood_id_idx').on(columns.moodID),
    index('payload_locked_documents_rels_knowledge_id_idx').on(columns.knowledgeID),
    index('payload_locked_documents_rels_knowledge_collections_id_idx').on(
      columns.knowledgeCollectionsID,
    ),
    index('payload_locked_documents_rels_conversation_id_idx').on(columns.conversationID),
    index('payload_locked_documents_rels_message_id_idx').on(columns.messageID),
    index('payload_locked_documents_rels_memory_id_idx').on(columns.memoryID),
    index('payload_locked_documents_rels_token_gifts_id_idx').on(columns.tokenGiftsID),
    index('payload_locked_documents_rels_subscription_payments_id_idx').on(
      columns.subscriptionPaymentsID,
    ),
    index('payload_locked_documents_rels_subscription_tiers_id_idx').on(
      columns.subscriptionTiersID,
    ),
    index('payload_locked_documents_rels_token_packages_id_idx').on(columns.tokenPackagesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['botID']],
      foreignColumns: [bot.id],
      name: 'payload_locked_documents_rels_bot_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['api-keyID']],
      foreignColumns: [api_key.id],
      name: 'payload_locked_documents_rels_api_key_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['moodID']],
      foreignColumns: [mood.id],
      name: 'payload_locked_documents_rels_mood_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['knowledgeID']],
      foreignColumns: [knowledge.id],
      name: 'payload_locked_documents_rels_knowledge_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['knowledgeCollectionsID']],
      foreignColumns: [knowledge_collections.id],
      name: 'payload_locked_documents_rels_knowledge_collections_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['conversationID']],
      foreignColumns: [conversation.id],
      name: 'payload_locked_documents_rels_conversation_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['messageID']],
      foreignColumns: [message.id],
      name: 'payload_locked_documents_rels_message_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['memoryID']],
      foreignColumns: [memory.id],
      name: 'payload_locked_documents_rels_memory_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tokenGiftsID']],
      foreignColumns: [token_gifts.id],
      name: 'payload_locked_documents_rels_token_gifts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['subscriptionPaymentsID']],
      foreignColumns: [subscription_payments.id],
      name: 'payload_locked_documents_rels_subscription_payments_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['subscriptionTiersID']],
      foreignColumns: [subscription_tiers.id],
      name: 'payload_locked_documents_rels_subscription_tiers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['tokenPackagesID']],
      foreignColumns: [token_packages.id],
      name: 'payload_locked_documents_rels_token_packages_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = sqliteTable(
  'payload_preferences',
  {
    id: integer('id').primaryKey(),
    key: text('key'),
    value: text('value', { mode: 'json' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = sqliteTable(
  'payload_preferences_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = sqliteTable(
  'payload_migrations',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    batch: numeric('batch'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_bot_speech_examples = relations(bot_speech_examples, ({ one }) => ({
  _parentID: one(bot, {
    fields: [bot_speech_examples._parentID],
    references: [bot.id],
    relationName: 'speech_examples',
  }),
}))
export const relations_bot_rels = relations(bot_rels, ({ one }) => ({
  parent: one(bot, {
    fields: [bot_rels.parent],
    references: [bot.id],
    relationName: '_rels',
  }),
  knowledgeCollectionsID: one(knowledge_collections, {
    fields: [bot_rels.knowledgeCollectionsID],
    references: [knowledge_collections.id],
    relationName: 'knowledgeCollections',
  }),
}))
export const relations_bot = relations(bot, ({ one, many }) => ({
  user: one(users, {
    fields: [bot.user],
    references: [users.id],
    relationName: 'user',
  }),
  picture: one(media, {
    fields: [bot.picture],
    references: [media.id],
    relationName: 'picture',
  }),
  speech_examples: many(bot_speech_examples, {
    relationName: 'speech_examples',
  }),
  _rels: many(bot_rels, {
    relationName: '_rels',
  }),
}))
export const relations_api_key = relations(api_key, ({ one }) => ({
  user: one(users, {
    fields: [api_key.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_mood = relations(mood, ({ one }) => ({
  user: one(users, {
    fields: [mood.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_knowledge_tags = relations(knowledge_tags, ({ one }) => ({
  _parentID: one(knowledge, {
    fields: [knowledge_tags._parentID],
    references: [knowledge.id],
    relationName: 'tags',
  }),
}))
export const relations_knowledge = relations(knowledge, ({ one, many }) => ({
  user: one(users, {
    fields: [knowledge.user],
    references: [users.id],
    relationName: 'user',
  }),
  tags: many(knowledge_tags, {
    relationName: 'tags',
  }),
  knowledge_collection: one(knowledge_collections, {
    fields: [knowledge.knowledge_collection],
    references: [knowledge_collections.id],
    relationName: 'knowledge_collection',
  }),
}))
export const relations_knowledge_collections_rels = relations(
  knowledge_collections_rels,
  ({ one }) => ({
    parent: one(knowledge_collections, {
      fields: [knowledge_collections_rels.parent],
      references: [knowledge_collections.id],
      relationName: '_rels',
    }),
    botID: one(bot, {
      fields: [knowledge_collections_rels.botID],
      references: [bot.id],
      relationName: 'bot',
    }),
  }),
)
export const relations_knowledge_collections = relations(
  knowledge_collections,
  ({ one, many }) => ({
    user: one(users, {
      fields: [knowledge_collections.user],
      references: [users.id],
      relationName: 'user',
    }),
    _rels: many(knowledge_collections_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_conversation_rels = relations(conversation_rels, ({ one }) => ({
  parent: one(conversation, {
    fields: [conversation_rels.parent],
    references: [conversation.id],
    relationName: '_rels',
  }),
  botID: one(bot, {
    fields: [conversation_rels.botID],
    references: [bot.id],
    relationName: 'bot',
  }),
}))
export const relations_conversation = relations(conversation, ({ one, many }) => ({
  user: one(users, {
    fields: [conversation.user],
    references: [users.id],
    relationName: 'user',
  }),
  _rels: many(conversation_rels, {
    relationName: '_rels',
  }),
}))
export const relations_message = relations(message, ({ one }) => ({
  user: one(users, {
    fields: [message.user],
    references: [users.id],
    relationName: 'user',
  }),
  conversation: one(conversation, {
    fields: [message.conversation],
    references: [conversation.id],
    relationName: 'conversation',
  }),
  bot: one(bot, {
    fields: [message.bot],
    references: [bot.id],
    relationName: 'bot',
  }),
}))
export const relations_memory = relations(memory, ({ one }) => ({
  user: one(users, {
    fields: [memory.user],
    references: [users.id],
    relationName: 'user',
  }),
  bot: one(bot, {
    fields: [memory.bot],
    references: [bot.id],
    relationName: 'bot',
  }),
  conversation: one(conversation, {
    fields: [memory.conversation],
    references: [conversation.id],
    relationName: 'conversation',
  }),
}))
export const relations_token_gifts = relations(token_gifts, ({ one }) => ({
  sender: one(users, {
    fields: [token_gifts.sender],
    references: [users.id],
    relationName: 'sender',
  }),
  receiver: one(users, {
    fields: [token_gifts.receiver],
    references: [users.id],
    relationName: 'receiver',
  }),
}))
export const relations_subscription_payments = relations(subscription_payments, ({ one }) => ({
  user: one(users, {
    fields: [subscription_payments.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_subscription_tiers_features = relations(
  subscription_tiers_features,
  ({ one }) => ({
    _parentID: one(subscription_tiers, {
      fields: [subscription_tiers_features._parentID],
      references: [subscription_tiers.id],
      relationName: 'features',
    }),
  }),
)
export const relations_subscription_tiers = relations(subscription_tiers, ({ many }) => ({
  features: many(subscription_tiers_features, {
    relationName: 'features',
  }),
}))
export const relations_token_packages = relations(token_packages, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    botID: one(bot, {
      fields: [payload_locked_documents_rels.botID],
      references: [bot.id],
      relationName: 'bot',
    }),
    'api-keyID': one(api_key, {
      fields: [payload_locked_documents_rels['api-keyID']],
      references: [api_key.id],
      relationName: 'api-key',
    }),
    moodID: one(mood, {
      fields: [payload_locked_documents_rels.moodID],
      references: [mood.id],
      relationName: 'mood',
    }),
    knowledgeID: one(knowledge, {
      fields: [payload_locked_documents_rels.knowledgeID],
      references: [knowledge.id],
      relationName: 'knowledge',
    }),
    knowledgeCollectionsID: one(knowledge_collections, {
      fields: [payload_locked_documents_rels.knowledgeCollectionsID],
      references: [knowledge_collections.id],
      relationName: 'knowledgeCollections',
    }),
    conversationID: one(conversation, {
      fields: [payload_locked_documents_rels.conversationID],
      references: [conversation.id],
      relationName: 'conversation',
    }),
    messageID: one(message, {
      fields: [payload_locked_documents_rels.messageID],
      references: [message.id],
      relationName: 'message',
    }),
    memoryID: one(memory, {
      fields: [payload_locked_documents_rels.memoryID],
      references: [memory.id],
      relationName: 'memory',
    }),
    tokenGiftsID: one(token_gifts, {
      fields: [payload_locked_documents_rels.tokenGiftsID],
      references: [token_gifts.id],
      relationName: 'tokenGifts',
    }),
    subscriptionPaymentsID: one(subscription_payments, {
      fields: [payload_locked_documents_rels.subscriptionPaymentsID],
      references: [subscription_payments.id],
      relationName: 'subscriptionPayments',
    }),
    subscriptionTiersID: one(subscription_tiers, {
      fields: [payload_locked_documents_rels.subscriptionTiersID],
      references: [subscription_tiers.id],
      relationName: 'subscriptionTiers',
    }),
    tokenPackagesID: one(token_packages, {
      fields: [payload_locked_documents_rels.tokenPackagesID],
      references: [token_packages.id],
      relationName: 'tokenPackages',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  bot_speech_examples: typeof bot_speech_examples
  bot: typeof bot
  bot_rels: typeof bot_rels
  api_key: typeof api_key
  mood: typeof mood
  knowledge_tags: typeof knowledge_tags
  knowledge: typeof knowledge
  knowledge_collections: typeof knowledge_collections
  knowledge_collections_rels: typeof knowledge_collections_rels
  conversation: typeof conversation
  conversation_rels: typeof conversation_rels
  message: typeof message
  memory: typeof memory
  token_gifts: typeof token_gifts
  subscription_payments: typeof subscription_payments
  subscription_tiers_features: typeof subscription_tiers_features
  subscription_tiers: typeof subscription_tiers
  token_packages: typeof token_packages
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_bot_speech_examples: typeof relations_bot_speech_examples
  relations_bot_rels: typeof relations_bot_rels
  relations_bot: typeof relations_bot
  relations_api_key: typeof relations_api_key
  relations_mood: typeof relations_mood
  relations_knowledge_tags: typeof relations_knowledge_tags
  relations_knowledge: typeof relations_knowledge
  relations_knowledge_collections_rels: typeof relations_knowledge_collections_rels
  relations_knowledge_collections: typeof relations_knowledge_collections
  relations_conversation_rels: typeof relations_conversation_rels
  relations_conversation: typeof relations_conversation
  relations_message: typeof relations_message
  relations_memory: typeof relations_memory
  relations_token_gifts: typeof relations_token_gifts
  relations_subscription_payments: typeof relations_subscription_payments
  relations_subscription_tiers_features: typeof relations_subscription_tiers_features
  relations_subscription_tiers: typeof relations_subscription_tiers
  relations_token_packages: typeof relations_token_packages
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-d1-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
